"""Squash previous migrations

Revision ID: 08a3083978c4
Revises: 
Create Date: 2024-12-17 12:41:42.507948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a3083978c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique_department_name', 'department', ['company_id', 'name'])
    op.create_unique_constraint('unique_path', 'department', ['company_id', 'path'])
    op.create_foreign_key(op.f('fk_department_head_id_user'), 'department', 'user', ['head_id'], ['id'])
    op.create_unique_constraint('unique_position_title', 'position', ['department_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_position_title', 'position', type_='unique')
    op.drop_constraint(op.f('fk_department_head_id_user'), 'department', type_='foreignkey')
    op.drop_constraint('unique_path', 'department', type_='unique')
    op.drop_constraint('unique_department_name', 'department', type_='unique')
    op.drop_column('department', 'head_id')
    # ### end Alembic commands ###
