"""Add department and position models

Revision ID: 72fc6c472b6a
Revises: 9607e8152d98
Create Date: 2024-12-16 13:36:23.627922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType


# revision identifiers, used by Alembic.
revision: str = '72fc6c472b6a'
down_revision: Union[str, None] = '9607e8152d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS ltree')
    op.create_table('department',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', LtreeType(), nullable=False),
    sa.Column('parent_department', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_department_company_id_company')),
    sa.ForeignKeyConstraint(['parent_department'], ['department.id'], name=op.f('fk_department_parent_department_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department'))
    )
    op.create_table('position',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_position_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position'))
    )
    op.create_table('userposition',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], name=op.f('fk_userposition_position_id_position')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_userposition_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userposition'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userposition')
    op.drop_table('position')
    op.drop_table('department')
    # ### end Alembic commands ###
