"""add constraints to models

Revision ID: ddee84bd17de
Revises: e461a454219f
Create Date: 2024-12-17 10:51:43.505789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddee84bd17de'
down_revision: Union[str, None] = 'e461a454219f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_department_name', 'department', ['company_id', 'name'])
    op.create_unique_constraint('unique_path', 'department', ['company_id', 'path'])
    op.create_unique_constraint('unique_position_title', 'position', ['department_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_position_title', 'position', type_='unique')
    op.drop_constraint('unique_path', 'department', type_='unique')
    op.drop_constraint('unique_department_name', 'department', type_='unique')
    # ### end Alembic commands ###
