"""add head of department field

Revision ID: e461a454219f
Revises: 72fc6c472b6a
Create Date: 2024-12-17 10:36:46.650352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e461a454219f'
down_revision: Union[str, None] = '72fc6c472b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userposition', sa.Column('is_head_of_department', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userposition', 'is_head_of_department')
    # ### end Alembic commands ###
